// Generated by CoffeeScript 1.4.0
(function() {
  var drawChart;

  window.db = new Firebase('https://coursegrapher.firebaseio.com/');

  window.database = {};

  window.departments_received = 0;

  window.revs = function(data, options) {
    var c, category, course, courses, dept, dept_name, name, obj, val, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3;
    departments_received++;
    dept_name = options.dept;
    dept = database[dept_name];
    _ref = data.values;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      obj = _ref[_i];
      courses = (function() {
        var _j, _len1, _ref1, _results;
        _ref1 = obj.section.aliases;
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          c = _ref1[_j];
          if (c.indexOf(dept_name) === 0) {
            _results.push(c.split('-')[1]);
          }
        }
        return _results;
      })();
      for (_j = 0, _len1 = courses.length; _j < _len1; _j++) {
        course = courses[_j];
        if (!dept[course]) {
          dept[course] = {
            reviews: [],
            totals: {},
            averages: {},
            name: options.dept_name
          };
        }
        c = dept[course];
        c.reviews.push(obj.ratings);
        _ref1 = obj.ratings;
        for (category in _ref1) {
          val = _ref1[category];
          if (!(category in c.totals)) {
            c.totals[category] = {
              sum: 0,
              num: 0
            };
          }
          c.totals[category].sum += parseFloat(val);
          c.totals[category].num++;
        }
      }
    }
    for (name in dept) {
      c = dept[name];
      _ref2 = c.totals;
      for (category in _ref2) {
        val = _ref2[category];
        c.averages[category] = val.sum / val.num;
        if (!(category in dept.totals)) {
          dept.totals[category] = {
            sum: 0,
            num: 0
          };
        }
        dept.totals[category].sum += c.averages[category];
        dept.totals[category].num++;
      }
      delete c.totals;
      delete c.reviews;
    }
    _ref3 = dept.totals;
    for (category in _ref3) {
      val = _ref3[category];
      dept.averages[category] = val.sum / val.num;
    }
    delete dept.totals;
    db.update(_.pick(database, dept_name));
    if (departments_fetched === departments_received) {
      return console.log("Done: " + departments_received + " departments processed");
    }
  };

  window.departments_fetched = 0;

  window.depts = function(data, options) {
    var d, _i, _len, _ref, _results;
    if (options == null) {
      options = {};
    }
    _ref = data.values;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      d = _ref[_i];
      if (!(d.id in database)) {
        departments_fetched++;
        options.dept = d.id;
        options.dept_name = d.name;
        database[d.id] = {
          totals: {},
          averages: {}
        };
        _results.push(dept_reviews(d.id, revs, _.clone(options)));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  google.load('visualization', '1', {
    'packages': ['motionchart']
  });

  google.setOnLoadCallback(drawChart);

  drawChart = function() {
    var data;
    data = new google.visualization.DataTable();
    data.addColumn('string', 'Major');
    data.addColumn('date', 'Date');
    data.addColumn('number', 'Instructor Quality');
    data.addColumn('number', 'Difficulty');
    data.addColumn('number', 'Course Quality');
    data.addColumn('number', 'Ability to Stimulate Interest');
    data.addColumn('number', 'Access to Instructor');
    data.addColumn('number', 'Amount Learned');
    data.addColumn('number', 'Amount of Work');
    data.addColumn('number', 'Instructor\'s Communication');
    data.addColumn('number', 'Recommended for Majors');
    data.addColumn('number', 'Recommended for Non-Majors');
    data.addColumn('number', 'Number of Reviews');
    return data.addRows();
  };

}).call(this);
