// Generated by CoffeeScript 1.4.0
(function() {
  var DOMAIN, get_json;

  DOMAIN = 'http://api.penncoursereview.com/v1/';

  get_json = function(path, callback, options) {
    var _this = this;
    return $.get("" + DOMAIN + path + "?token=" + TOKEN, function(data) {
      data = JSON.parse(data).result;
      return callback(data, options);
    });
  };

  window.review = function(cid, sid, iid, callback, options) {
    var path;
    path = "courses/" + cid + "/sections/" + sid + "/reviews/" + iid;
    return get_json(path, callback, options);
  };

  window.instructor = function(iid, callback, options) {
    var path;
    path = "instructors/" + iid;
    return get_json(path, callback, options);
  };

  window.section = function(cid, sid, callback, options) {
    var path;
    path = "courses/" + cid + "/sections/" + sid;
    return get_json(path, callback, options);
  };

  window.course = function(cid, callback, options) {
    var path;
    path = "courses/" + cid;
    return get_json(path, callback, options);
  };

  window.course_history = function(chid, callback, options) {
    var path;
    path = "coursehistories/" + chid;
    return get_json(path, callback, options);
  };

  window.department = function(did, callback, options) {
    var path;
    path = "depts/" + did;
    return get_json(path, callback, options);
  };

  window.departments = function(callback, options) {
    var path;
    path = 'depts/';
    return get_json(path, callback, options);
  };

  window.ch_reviews = function(chid, callback, options) {
    var path;
    path = "coursehistories/" + chid + "/reviews";
    return get_json(path, callback, options);
  };

  window.dept_reviews = function(did, callback, options) {
    var path;
    path = "depts/" + did + "/reviews";
    return get_json(path, callback, options);
  };

}).call(this);
